#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

DISP_NUM=`xrandr -d :0 -q | grep ' connected' | wc -l`
RESOLUTION=`xrandr | grep \* | cut -d' ' -f4`
if [ $DISP_NUM -eq 2 ];
then
        bspc monitor DP-0 -d web code chat
        bspc monitor DP-2 -d video game torrent
        #polybar top_ext > /dev/null 2>&1 &
        mons -e top
else
        if [ $RESOLUTION = '1080x1920' ];
        then
          bspc monitor -d web code server
        else
          bspc monitor -d web code chat video game torrent server
        fi
        #bspc monitor DP-0 -d web code chat video game torrent server
fi

pkill polybar

$HOME/.config/polybar/launch.sh

pkill picom
picom &
#fcitx-autostart &
remmina -i &
pkill keepassxc
/usr/bin/keepassxc &
xscreensaver -no-splash &
#caffeine &
#polybar example &
blueman-applet &
#solaar &

pkill plank
plank &

pkill guake
guake &

/usr/bin/lxqt-policykit-agent &
octopi-notifier &

pkill dunst
dunst &


#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor eDP1 -d tty www dev opt
#bspc monitor HDMI1 -d tty www dev opt

bspc config border_width        0.5
bspc config window_gap          1
bspc config top_padding         1


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Focusing behavior
bspc config focus_follows_pointer     true
bspc config history_aware_focus     true
bspc config focus_by_distance     true

#Multihead behavior
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a org.remmina.Remmina desktop='^7' state=floating follow=on
bspc rule -a telegram-desktop desktop='^3' state=floating follow=on
bspc rule -a Chromium desktop='^1' follow=on
bspc rule -a atom desktop='^4' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^1' follow=on



wal -i Pictures/bg.png

# Remap Caps key to control
setxkbmap -option ctrl:nocaps

systemd-detect-virt 1> /dev/null
if [ $? == 0 ];
then
  # Run virtualbox-tools
  VboxClient-all
fi

