#!/bin/bash

xgetmons() {
    xrandr | grep \ connected | awk {'print $1'}
}

pgrep -x sxhkd > /dev/null || sxhkd &

DISP_NUM=$(xrandr -d :0 -q | grep -c ' connected')
RESOLUTION=$(xrandr | grep ".*" | cut -d' ' -f4)
INTERNAL=$(xgetmons | grep eDP)
EXTERNAL=$(xgetmons | grep -v eDP)

if [ "$DISP_NUM" -eq 2 ];
then
        dunstify "Using dual monitor setup"
        bspc monitor "$INTERNAL" -d web code chat
        for mons in $EXTERNAL ; do
          bspc monitor "$mons" -d video game torrent
        done
else
        if [ "$RESOLUTION" = '1080x1920' ];
        then
          bspc monitor -d web code server
        else
          dunstify "Using single monitor setup"
          bspc monitor "$INTERNAL" -d web code chat video game torrent server
        fi
fi


bspc config border_width        0.5
bspc config window_gap          1
bspc config top_padding         1


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Focusing behavior
#
bspc config focus_follows_pointer     true
#bspc config click_to_focus true

#Multihead behavior
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc rule -a Gimp desktop='^4' state=floating follow=on
#bspc rule -a org.remmina.Remmina desktop='^7' state=floating follow=on
bspc rule -a telegram-desktop desktop='^3' state=floating follow=on
bspc rule -a Chromium desktop='^1' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^1' follow=on
# To fix weried and annoying bug with jetbrain products
bspc rule -a android-studio state=floating border=off follow=on
# To fix weried and annoying bug with jetbrain products * 2
bspc rule -a intellij state=floating border=off follow=on


pkill wmname
wmname LG3D &

#remmina -i &
#pkill keepassxc
#/usr/bin/keepassxc &

pkill xscreensaver
xscreensaver -no-splash &

#blueman-applet &

AUTO_START=(caffeine picom plank dunst guake keepassxc blueman-applet redshift lxqt-policykit-agent nm-applet)
for p in "${AUTO_START[@]}"; do
  pgrep -x "$p" > /dev/null || $p & disown
done

pgrep -x fcitx > /dev/null || fcitx -u fcitx-light-ui &

wal -i wallpapers/awesome.png

"$HOME"/.config/polybar/launch.sh & disown

# Remap Caps key to control
#setxkbmap -option ctrl:nocaps

systemd-detect-virt 1> /dev/null

if [ $? == 0 ];
then
  # Run virtualbox-tools
  VboxClient-all
fi

notify-send "Desktop loaded successfully" "$(date +'%c')"
